services:
  db:
    extends:
      file: compose.yml
      service: db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  crawler:
    image: schemacrawler/schemacrawler:latest
    volumes:
      - docs:/home/schcrwlr/share
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:
  docs:
