version: "3.8"
networks:
  default:
  reverse-proxy:
    external: true
services:
  api:
    container_name: checklist-manager-api-${ENVIRONMENT}
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    env_file:
      - .env
    networks:
      - reverse-proxy
    volumes:
      - static:/code/static
      - attachments:/code/attachments
    image: checklist-manager/backend-${ENVIRONMENT}
  nginx:
    container_name: checklist-manager-nginx-${ENVIRONMENT}
    build:
      dockerfile: ./nginx/Dockerfile
      context: ./
      args:
        - PUBLIC_URL
        - API_URL
        - ENVIRONMENT
    restart: always
    env_file:
      - .env
    volumes:
      - static:/static
      - attachments:/attachments
      - ./nginx/defalt.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
volumes:
  static:
  attachments:
