name: Documentation
on:
  push:
    branches:
      - dev
jobs:
  mkdocs:
    permissions:
      contents: write
    name: Documentation
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.8.1
          installer-parallel: true
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Install dependencies
        run: poetry -C backend install --with docs
      - name: Build documentation
        run: poetry -C backend run mkdocs build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc_site
