name: SonarCloud
on:
  push:
    branches:
      - main
      - dev
jobs:
  sonarcloud:
    name: SonarCloud
    env:
      ENVIRONMENT: "demo"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.7.0
          installer-parallel: true
      - name: Install dependencies
        run: poetry -C backend install --with test
      - name: Test for coverage
        run: poetry -C backend run coverage run backend/manage.py test backend &&
          poetry -C backend run coverage xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=HomeLabHQ_checklist-manager
            -Dsonar.organization=homelabhq
            -Dsonar.exclusions=docs/**
            -Dsonar.python.coverage.reportPaths=coverage.xml
